[package]
name = "yancy"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.5.50", features = ["derive"] }
cxx = "1.0"
image = "0.25.8"
imageproc = "0.25.0"
nalgebra = "0.34.1"
openmp-sys = "1.3.0"
rayon = "1.11.0"

[build-dependencies]
cxx-build = "1.0"
